### ISSUE TITLE
Criacao Core entre Fexextension e FexAPI

### ISSUE THREAD

**Issue by joaopaulovramos** [flask-extensions/flaskextensions.com#21]
Vou criar o CORE para separar as camadas, um middleware.
A tecnologia achada foi do Python RDP. O Bruno tinha falado sobre RDC, mas nao achei muita coisa por ser um termo muito abrangente em varias areas.

**Comment by rochacbruno** [comment]
Esta parte já está coberta pelo docker, vamos por enquanto manter API e Service falando diretamente com o banco de dados.
