### ISSUE TITLE
Mudanca do Banco SQL para Elasticsearch

### ISSUE THREAD

**Issue by joaopaulovramos** [flask-extensions/flaskextensions.com#24]
Criarei uma conexao e o CRUD  para Elasticsearch.

**Comment by MarcusMann** [comment]
Será que realmente é necessário usa Elasticsearch? @jairomr @marcosf63 @rochacbruno

**Comment by rochacbruno** [comment]
Eu to pensando em usar o Postresql full text search mesmo

**Comment by jairomr** [comment]
Eu não sei muito de banco de dados, e não conheço o Elasticsearch. Então deixo está escolha para vocês.
