### ISSUE TITLE
Criar um changelog/tags para manter o histórico das releases

### ISSUE THREAD

**Issue by mtrsk** [flask-extensions/flaskextensions.com#29]
O projeto atualmente já passou dos 100 commits (a maioria do bot), seria bom depois manter algumas tags bonitinhas, criar um `CHANGELOG.md` e manter alguma forma de [versionamento semântico](https://semver.org/lang/pt-BR/).

**Comment by Pbezerra-dev** [comment]
Ja está em desenvolvimento!

**Comment by Pbezerra-dev** [comment]
yes my vote is MIT :)
