### ISSUE TITLE
Criar API com FASTAPI

### ISSUE THREAD

**Issue by rochacbruno** [flask-extensions/flaskextensions.com#3]
![Screenshot_2020-03-27_00-06-51](https://user-images.githubusercontent.com/458654/77718765-737afd00-6fc2-11ea-932c-0c606449c15d.png)

**Comment by cuducos** [comment]
I'm happy to help here. Is anyone else working on that?

**Comment by rochacbruno** [comment]
@cuducos vamos fazer ao vivo no Twitch :) esta enquete surgiu em https://www.twitch.tv/videos/576291209?t=00h06m49s

**Comment by rochacbruno** [comment]
@cuducos bora participar? Quintas as 21:30 no twitch

**Comment by cuducos** [comment]
Dificilmente. Normalmente dia de semana de noite é da família 💜 Mas se der, apareço! Obrigado
